version: 1.2
workflows:
   - subclass: WDL
     primaryDescriptorPath: /covstats_and_indexcov.wdl
     testParameterFiles:
         - /covstats_and_indexcov.json
     name: covstats_and_indexcov
   - subclass: WDL
     primaryDescriptorPath: covstats.wdl
     name: covstats
   - subclass: WDL
     primaryDescriptorPath: /indexcov.wdl
     name: indexcov
     authors:
         - name:  Nayeon
